version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: user-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: