apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    maxSize: 3
    ssh:
      publicKeyName: my-key-pair