apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: <your-ecr-repo-uri>:<tag>
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILE
              value: /app/config/config.prod.yaml